zambodaniel_sylius_foxpost_shop:
    resource: "@ZamboDanielSyliusFoxpostPlugin/Resources/config/routes/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

zambodaniel_sylius_foxpost_admin:
    resource: "@ZamboDanielSyliusFoxpostPlugin/Resources/config/routes/admin.yaml"
    prefix: /admin
